---
- name: Failover To Backup via Pipelines
  hosts: csr1000v

  tasks:
    - name: Configure Multiple interfaces
      cisco.ios.ios_config:
        parents: "{{ item }}"
        lines:
          - no shut
       
        save_when: modified
      with_items:
        - interface Ethernet0/2