---
- name: Failover To Backup via Pipelines
  hosts: core-switch-01
  gather_facts: false

  tasks:
    - name: Configure Multiple interfaces
      cisco.ios.ios_config:
        parents: "{{ item }}"
        lines:
          - shutdown
        save_when: modified
      with_items:
        - interface Ethernet0/2