---
- name: Unstable Backhaul Links
  hosts: Core-PE1
  gather_facts: false

  tasks:
    - name: shutdown preferred Path
      cisco.ios.ios_config:
        parents: "{{ item }}"
        lines:
          - shutdown
        save_when: modified

      with_items:
        - interface Ethernet0/1