---
- name: Facts
  hosts: csr1000v
  gather_facts: false
  tasks:
  
    - name: Gather Fcts - 01
      cisco.ios.facts:
       gather_subset: all
      register: all_subset
     
    - name: PRINT ALL SUBSETS GATHERED
      debug:
        var: all_subset
