---
- name: Facts
  hosts: csr1000v
  gather_facts: false
  tasks:

    - name: Gather all legacy facts
      cisco.ios.ios_facts:
       gather_subset: all
  
    - name: Gather Fcts - 01
      cisco.ios.ios_facts:
       gather_subset: all
      register: all_subset
     
    - name: PRINT ALL SUBSETS GATHERED
      debug:
        var: all_subset

        
    - name: Gather HW
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: hw
    - name: Print HW
      debug:
        var: hw


    - name: Gather Int
      cisco.ios.ios_facts:
        gather_subset: interfaces
      register: int
    - name: Print Interfaces
      debug:
        var: int 
